authc/urls.py
from django.urls import include, path
from . import views

app_name = "authc"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("open/", views.OpenView.as_view(), name="open"),
    path("apereo/", views.ApereoView.as_view(), name="apereo"),
    path("manual_protect/", views.ManualProtect.as_view(), name="manual_protect"),
    path("protect_view/", views.ProtectView.as_view(), name="protect_view"),
    path("dump_python/", views.DumpPython.as_view(), name="dump_python"),
    path("example/", views.example, name="example"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("forms/", include("forms.urls")),
    path("authc/", include("authc.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

polls/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.users, name="users"),
    path("user/<int:id>", views.user_details, name="user_details"),
    path("template", TemplateView.as_view(template_name="main.html"), name="template"),
    path("rest/<int:guess>", views.rest, name="rest"),
    path("danger", views.danger, name="danger"),
    path("redirect", views.Redirect.as_view(), name="redirect"),
    path("cats", views.CatsListView.as_view(), name="cats"),
    path("cat/<int:id>", views.CatDetailView.as_view(), name="cat_detail"),
    path("dogs", views.DogsListView.as_view(), name="dogs"),
    path("dogs/<int:id>", views.DogDetailView.as_view(), name="dog_detail"),
]

polls/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=128)
    email = models.CharField(max_length=128)


class Cat(models.Model):
    name = models.CharField(max_length=128)


class Dog(models.Model):
    name = models.CharField(max_length=128)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Cat, Dog, User
from django.views import generic, View
from django.utils.html import escape


# Create your views here.
def users(request):
    users = User.objects.values("id", "name")
    print(users)
    context = {"users": users}
    return render(request, "users.html", context)


def user_details(request, id):
    user = User.objects.filter(id=int(id)).all()
    context = {"user_detail": user}
    return render(request, "user.html", context)


class ListView(View):
    model = Cat

    def get(self, request):
        modelname = self.model._meta.verbose_name.title().lower()
        stuff = self.model.objects.all()
        context = {f"{modelname}_list": stuff}
        return render(request, f"animals/{modelname}_list.html", context)


class DetailView(View):
    model = Cat

    def get(self, request, id):
        modelname = self.model._meta.verbose_name.title().lower()
        name = self.model.objects.filter(id=int(id)).values("name")
        context = {f"{modelname}_detail": name}
        return render(request, f"animals/{modelname}_detail.html", context)


class CatsListView(ListView):
    model = Cat


class CatDetailView(DetailView):
    model = Cat


class DogsListView(ListView):
    model = Dog


class DogDetailView(DetailView):
    model = Dog


def rest(request, guess):
    return HttpResponse(f"The integer value passed in the URL is: {guess}")


class Danger(View):
    def get(self, request):
        html = (
            """<html><body><p>Your guess was """
            + request.GET["guess"]
            + """</p></body></html>"""
        )

        return render(request, html)


def danger(request):
    html = f"""<html><body><p>Your guess was {request.GET.get('guess')}</p></body></html>"""
    return HttpResponse(html)


class Redirect(View):
    def get(self, request):
        return HttpResponseRedirect("http://127.0.0.1:8000/polls")

polls/templates/main.html
{% extends "template.html" %} {%block content%}
<h1>Directly Render Template to URLS</h1>
{%endblock%}

polls/templates/template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Practice</title>
  </head>
  <body>
    <h1>Hello From Django</h1>
    <p>This is a inherited template</p>
    <nav>
      <ul>
        <li><a href="{% url 'polls:users' %}">Users</a></li>
        <li><a href="{% url 'polls:template' %} ">Template</a></li>
        <li><a href="{% url 'polls:rest' 42%}">Rest</a></li>
        <li><a href="{% url 'polls:danger' %}">Danger</a></li>
        <li><a href="{% url 'polls:redirect' %}">Redirect</a></li>
        <li><a href="{% url 'polls:cats' %}">Cats</a></li>
        <li><a href="{% url 'polls:dogs' %}">Dogs</a></li>
      </ul>
    </nav>

    {%block content%} {%endblock%}
  </body>
</html>

polls/templates/user.html
{%extends 'template.html'%} {%block content%} {% for user in user_detail %}

<h3>{{user.id}}: {{user.name}}</h3>
<p>{{user.email}}</p>
{% endfor %}
<a href="{% url 'polls:users' %}">Go back to users list</a>
{% endblock%}

polls/templates/users.html
{%extends 'template.html'%} {% block content%}
<h2>List of Registered Users</h2>
<ol type="1">
  {% for user in users %}
  <li>
    <a href="{% url 'polls:user_details' user.id %}">{{user.name}}</a>
  </li>
  {% endfor %}
</ol>
{%endblock%}