authc/urls.py
from django.urls import include, path
from . import views

app_name = "authc"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("open/", views.OpenView.as_view(), name="open"),
    path("apereo/", views.ApereoView.as_view(), name="apereo"),
    path("manual_protect/", views.ManualProtect.as_view(), name="manual_protect"),
    path("protect_view/", views.ProtectView.as_view(), name="protect_view"),
    path("dump_python/", views.DumpPython.as_view(), name="dump_python"),
    path("example/", views.example, name="example"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("forms/", include("forms.urls")),
    path("authc/", include("authc.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

authc/models.py
from django.db import models

# Create your models here.

authc/forms.py
from django import forms
from django.core import validators


class BasicForm(forms.Form):
    title = forms.CharField(validators=[validators.MinLengthValidator(2, "...")])
    mileage = forms.IntegerField()
    purchase_date = forms.DateField()

authc/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.utils.http import urlencode
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import BasicForm
from django.http import HttpResponse


# Create your views here.
class Home(View):
    def get(self, request):
        return render(request, "authc_template.html")


class OpenView(View):
    def get(self, request):
        return render(request, "open.html")


class ApereoView(View):
    def get(self, request):
        return render(request, "apereo.html")


class ManualProtect(View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, "manual.html")
        loginurl = reverse("login") + "?" + urlencode({"next": request.path})
        return redirect(loginurl)


class ProtectView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "protected.html")


class DumpPython(View):
    def get(self, request):
        return render(request, "dump.html")


def example(request):
    old_data = {"title": "Saki Car", "mileage": 42, "purchase_date": "2024-02-24"}
    form = BasicForm(old_data)
    context = {"form": form}
    return render(request, "example_form.html", context)

authc/templates/apereo.html
{% extends 'authc_template.html'%} {% block content %}
<h2>Apereo</h2>
{% endblock%}

authc/templates/authc_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Authentication</title>
  </head>
  <body>
    <h1>
      Current Request Path:
      <span style="color: deeppink">{{request.path}}</span>
    </h1>

    {% if user.is_authenticated %}
    <p>Authenticated As:</p>
    <pre>
      Name: {{user.username}}
      Email: {{user.email}}
      ID: {{user.id}}
    </pre>
    <p>
      You can <a href="{% url 'login' %}?next={% url 'authc:open' %}">Logout</a>
    </p>
    {% else %}
    <p>You are not Loged in</p>
    <p>
      You can <a href="{% url 'login' %}?next={{ request.path }}">Login</a> if
      you want
    </p>
    {% endif %}
    <nav>
      <ul>
        <li><a href="{% url 'authc:home' %}">Home</a></li>
        <li>
          <a href="{% url 'authc:open' %}">{% url 'authc:open' %}</a>
          (no login required)
        </li>
        <li>
          <a href="{% url 'authc:apereo' %}">{% url 'authc:apereo' %}</a> (no
          login required)
        </li>
        <li>
          <a href="{% url 'authc:manual_protect' %}"
            >{% url 'authc:manual_protect' %}</a
          >
          (protected by user.is_authenticated)
        </li>
        <li>
          <a href="{% url 'authc:protect_view' %}"
            >{% url 'authc:protect_view' %}</a
          >
          (protected by LoginRequiredMixin)
        </li>
        <li>
          <a href="{% url 'authc:dump_python' %}"
            >{% url 'authc:dump_python' %}</a
          >
          ( dump request. user data in python )
        </li>
        <li>
          <a href="{% url 'authc:example' %}">{% url 'authc:example' %}</a>
          ( example form )
        </li>
      </ul>
    </nav>
    {% block content%} {% endblock%}
  </body>
</html>

authc/templates/dump.html
{% extends 'authc_template.html' %} {% block content %}
<h2>Dump Python</h2>
{% endblock%}

authc/templates/example_form.html
{% extends 'authc_template.html' %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    value="Cancel"
    onclick="window.location = '{% url 'authc:home' %}'; return false;"
  />
</form>
{% endblock %}

authc/templates/manual.html
{% extends 'authc_template.html' %} {% block content %}
<h2>Manual Protect</h2>
{% endblock%}

authc/templates/open.html
{% extends 'authc_template.html' %} {% block content %}
<h2>Open</h2>
{% endblock %}

authc/templates/protected.html
{% extends 'authc_template.html' %} {% block content %}
<h2>Protected View</h2>
{% endblock%}